# Hexo 配置
## 文档：https://hexo.io/docs/configuration.html
## 来源：https://github.com/hexojs/hexo/

# 站点
title: 爱分享
subtitle: '52UE'
description: '虚幻引擎资源分享'
keywords: 
  - 虚幻引擎
  - 资源分享
  - 52UE
author: 白眼狼
language: zh-CN
timezone: ''

# URL
## 在此设置您的站点URL。例如，如果使用GitHub Pages，请将url设置为'https://username.github.io/project'
url: https://52ue.com
root: /
permalink: posts/:abbrlink/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# 目录
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# 写作
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: post # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
  exclude_languages: ['mermaid']
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''
  exclude_languages: ['mermaid']

# 主页设置
# path: 博客索引页的根路径。(默认 = '')
# per_page: 每页显示的文章数。(0 = 禁用分页)
# order_by: 文章排序。(默认按日期降序排列)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# 分类 & 标签
default_category: uncategorized
category_map:
tag_map:

# 元数据元素
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# 日期 / 时间格式
## Hexo使用Moment.js解析和显示日期
## 您可以按以下定义自定义日期格式
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# 分页
## 将per_page设为0以禁用分页
per_page: 10
pagination_dir: page

# 包含 / 排除文件
## include:/exclude: 选项仅适用于'source/'文件夹
include:
exclude:
ignore:

# 扩展
## 插件：https://hexo.io/plugins/
## 主题：https://hexo.io/themes/
theme: butterfly

# 部署
## 文档：https://hexo.io/docs/one-command-deployment
deploy:
#  - type: 'git'
#    repo: git@github.com:BUXIN-A/buxin-a.github.io.git
#    branch: main
#  - type: 'indexnow_url_submitter'

# 渲染器
markdown:
  plugins:
    - '@renbaoshuo/markdown-it-katex'

# 搜索
search:
  path: search.xml
  field: post
  content: true
  format: striptags

# 永久链接
abbrlink:
  alg: crc16      #support crc16(default) and crc32
  rep: dec        #support dec(default) and hex
  allow: ['post','school','cpp',"java","blog"] #Allowed template types. The default is (" post ")
  disallow: [] #Unallowed template type. Default is an empty list

# 网站地图
sitemap:
    path: sitemap.xml
hexo_indexnow:
  count: 1 # number or "latest"
  txt_name: example.txt # links file name
  apikey: example # indexNow Apikey
  server: example # The server that received the request
               # For example: bing, yandex, indexnow
  log_urls: false # Log url list on output log

# 微软分析
analytics:
  microsoft_clarity:
    enable: true
    project_id: #微软分析ID

# tag-plugins-plus
# see https://akilar.top/posts/615e2dec/
tag_plugins:
  enable: true # 开关
  priority: 5 #过滤器优先权
  issues: false #issues标签依赖注入开关
  link:
    placeholder: /img/link.png #link_card标签默认的图标图片
  CDN:
    anima: /css/font-awesome-animation.min.css #动画标签anima的依赖
    jquery: /js/jquery.min.js #issues标签依赖
    issues: /js/issues.js #issues标签依赖
    iconfont: /js/iconfont.js #参看https://akilar.top/posts/d2ebecef/
    carousel: /js/carousel-touch.js
    tag_plugins_css: /css/tag_plugins.css

hexo_graph:
  echarts_js: "/js/echarts.min.js"